-- ═══════════════════════════════════════════════════════════════════════
-- V1__initial_schema.sql
-- Perishable Platform — Initial Database Schema
--
-- Managed by Flyway — DO NOT edit this file after deployment.
-- Create V2__ migration for any changes instead.
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS users (
    id               INT            NOT NULL AUTO_INCREMENT,
    username         VARCHAR(30)    NOT NULL,
    password_hash    VARCHAR(72)    NOT NULL,          -- BCrypt hash, never plain text
    role             ENUM('CUSTOMER','STORE_ADMIN','PLATFORM_ADMIN') NOT NULL DEFAULT 'CUSTOMER',
    wallet_balance   DECIMAL(12,2)  NOT NULL DEFAULT 0.00,
    created_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at    DATETIME       NULL,

    PRIMARY KEY (id),
    UNIQUE INDEX idx_users_username (username)
);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS suppliers (
    id                    INT           NOT NULL AUTO_INCREMENT,
    name                  VARCHAR(100)  NOT NULL,
    contact_number        VARCHAR(15)   NOT NULL,
    email                 VARCHAR(100)  NULL,
    category              ENUM('MILK','FRUIT','VEGETABLE','BAKERY') NOT NULL,
    avg_delivery_hours    DOUBLE        NOT NULL DEFAULT 24.0,
    reliability_score     DOUBLE        NOT NULL DEFAULT 1.0   COMMENT '0.0–1.0, updated via EMA on deliveries',
    is_active             BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_suppliers_category (category),
    INDEX idx_suppliers_active (is_active)
);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS products (
    id                  INT            NOT NULL AUTO_INCREMENT,
    name                VARCHAR(255)   NOT NULL,
    description         TEXT           NULL,
    base_price          DECIMAL(10,2)  NOT NULL           COMMENT 'Admin-set original price',
    dynamic_price       DECIMAL(10,2)  NOT NULL           COMMENT 'Expiry-adjusted price, updated nightly',
    category            ENUM('MILK','FRUIT','VEGETABLE','BAKERY') NOT NULL,
    expiry_date         DATE           NOT NULL,
    stock_quantity      INT            NOT NULL DEFAULT 0,
    units_sold_total    INT            NOT NULL DEFAULT 0  COMMENT 'Lifetime units sold, used for demand forecasting',
    units_wasted_total  INT            NOT NULL DEFAULT 0  COMMENT 'Lifetime units wasted, used for wastage analytics',
    supplier_id         INT            NOT NULL,
    added_at            DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_at     DATETIME       NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_products_category (category),
    INDEX idx_products_expiry (expiry_date),
    INDEX idx_products_stock (stock_quantity),
    FULLTEXT INDEX idx_products_search (name, description),  -- For fast text search
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS orders (
    id              INT            NOT NULL AUTO_INCREMENT,
    user_id         INT            NOT NULL,
    total_amount    DECIMAL(12,2)  NOT NULL,
    payment_method  ENUM('CASH','WALLET') NOT NULL,
    status          ENUM('PENDING','CONFIRMED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    placed_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_orders_user (user_id),
    INDEX idx_orders_placed (placed_at),
    INDEX idx_orders_status (status),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS order_lines (
    id              INT            NOT NULL AUTO_INCREMENT,
    order_id        INT            NOT NULL,
    product_id      INT            NOT NULL,
    product_name    VARCHAR(255)   NOT NULL   COMMENT 'Snapshot at order time — product may change later',
    quantity        INT            NOT NULL,
    price_per_unit  DECIMAL(10,2)  NOT NULL   COMMENT 'Dynamic price snapshotted at order time',

    PRIMARY KEY (id),
    INDEX idx_order_lines_order (order_id),
    INDEX idx_order_lines_product (product_id),
    FOREIGN KEY (order_id)   REFERENCES orders(id)   ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS wastage_records (
    id              INT            NOT NULL AUTO_INCREMENT,
    product_id      INT            NOT NULL,
    product_name    VARCHAR(255)   NOT NULL  COMMENT 'Snapshot — product may be deleted',
    units_wasted    INT            NOT NULL,
    value_wasted    DECIMAL(12,2)  NOT NULL  COMMENT 'units_wasted × base_price at time of wastage',
    recorded_on     DATE           NOT NULL,
    reason          ENUM('EXPIRY','DAMAGE','QUALITY_ISSUE') NOT NULL DEFAULT 'EXPIRY',

    PRIMARY KEY (id),
    INDEX idx_wastage_product  (product_id),
    INDEX idx_wastage_date     (recorded_on),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
